export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const CLEAR_WATCHLIST = "CLEAR_WATCHLIST";
export const IS_ITEM_IN_WATCHLIST = "IS_ITEM_IN_WATCHLIST";